# Site settings
title: Christopher Mason
email: cmason@cmason.com
description: 
  Software engineering leader who is passionate about creating
  powerful and usable software that betters the human condition.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cmason.com" # the base hostname & protocol for your site
destination: public
github_username:  masoncj
linkedin_url: https://www.linkedin.com/in/christopher-mason-510a291/

safe: false

theme: jekyll-theme-slate

collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /posts/:path/
  talks:
    output: true
    permalink: /talks/:path/
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      excerpt_separator: <!--more-->


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

relative_links:
  enabled:     true
  collections: true  

plugins:
  - jekyll-paginate
  - jekyll-babel
  - jekyll-relative-links
  - jekyll-sitemap

exclude:
  - .idea
  - .next
  - .sass-cache
  - components
  - interfaces
  - pages
  - next.config.js
  - next-env.d.ts
  - package.json
  - pnpm-lock.yaml
  - tsconfig.json
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md


babel_js_extensions: 'es6'
