# Site settings
title: Christopher Mason
email: cmason@cmason.com
description: 
  Software developer and manager who is passionate about creating
  powerful and usable software that solves real world problems.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www2.cmason.com" # the base hostname & protocol for your site
github_username:  masoncj

theme: jekyll-theme-slate

collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /posts/:path/
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      excerpt_separator: <!--more-->
#  - 
#    scope:
#      path: ""
#      type: projects
#    values:
#      layout: project

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

relative_links:
  enabled:     true
  collections: true  

gems:
  - jekyll-paginate
  - jekyll-babel
  - jekyll-relative-links

babel_js_extensions: 'es6'
